### ISSUE TITLE
In the popout, refreshing closes the widget

### ISSUE THREAD

**Issue by TomOffringa** [VoIPGRID/click-to-dial#13]
In the popout, refreshing closes the widget, the current version doesn’t & it has no widget open/close button

**Comment by cpoppema** [comment]
This is still happening (since I cannot build I tested it from the supplied 2.0.12 zip for Chrome):

Expected behavior:
- popout never ever closes its contact widget

Actual behavior:
- refreshing closes the popout contacts
- closing contacts in the popup, closes it in the popout
- opening contacts in the popup, does nothing in the popout
